version: '3.8'
services:
  top-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /opt/nest_store/.env:/opt/nest_store/.env:ro