version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
# version: '3.8'
# services:
#   top-api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: top-api
#     restart: always
#     ports:
#       - 3000:3000
#     environment:
#       - DATABASE_HOST=your-database-container-name
#       - DATABASE_PORT=your-database-port
#       - DATABASE_USERNAME=your-username
#       - DATABASE_PASSWORD=your-password
#       - DATABASE_NAME=your-db-name
#     networks:
#       - my-network

# networks:
#   my-network:
#     external: true
